<StartWindow>:
    id: start_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'eye2.png'
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: start_window.space_x, 660
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,605)
        Label:
            text: 'Welcome to e-vision clinic'
            bold: True
            font_size: '35'
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: start_window.space_x, 220
        Label:
            text: "[b]Follow simple steps & know about your vision[/b]"
            color: 0,0,0,1
            font_size: '30'
            markup: True
            size_hint_y: None
            height: 10
        Label:
            size_hint_y: None
            height: 140
        Button:
            id: start
            text: 'Start'
            background_color: (0,.3,.3,1)
            font_size: '25'
            on_press: root.manager.current = 'info'        
<InfoWindow>:
    id: info_window
    orientation: "vertical"
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: info_window.space_x, 660
        size_hint_y: None
        height: 100
        canvas:
            Color:
                rgba: (0,0.5,0.5,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'eye1.jpeg'
        Label:
            text: 'Fill your information below'
            font_size: '30'
            bold: True
    BoxLayout:
        padding: info_window.space_x-200, 130,info_window.space_x-100, 200
        spacing: 10
        BoxLayout:            
            Label:
                text: "\n\nName:\n\n\n\nAge:\n\n\n\nPlace:\n\n\n\nContact Number:"
                font_size: '20'
                color: 0,0,0,1
                halign: 'left'
        BoxLayout:
            orientation: 'vertical'
            spacing: 50
            background_color:(0,1,1,0)
            Label:
                id: information
                text: ""
                markup: True
                font_size: '20'
                size_hint_y: None
                height: 5
            TextInput: 
                id: name
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: age
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: place
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: number
                multiline: False
                write_tab: False
                font_size: '20'
    BoxLayout:
        orientation: 'vertical'
        padding: info_window.space_x, 100
        Label:
            size_hint_y: None
            height: 430
        Button:
            id: signin
            text: 'Submit'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.validate()
        
<SelectWindow>:
    id: select_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'eye3.jpg'
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: select_window.space_x, 660
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,605)
        Label:
            text: 'Choose a test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 120
        padding: select_window.space_x+50, 150
        Button:
            id: start
            text: 'Visual Acuity Test'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'acuity' 
        Button:
            id: start
            text: 'Astigmatism Test'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'astigma' 
        Button:
            id: start
            text: 'Glass Checker'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'glass' 
              
<VisualAcuityWindow>:
    id: visual_acuity
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: visual_acuity.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'visualAcuity.jpeg'
        Label:
            text: 'Visual Acuity Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        BoxLayout:
            padding: visual_acuity.space_x+200, 300, visual_acuity.space_x, 30
            Label:
                text: 
                    '''[b]Follow the instructions given below:[/b]\n
                    1. Remove your glasses\n
                    2. Stand 1 meter away from the monitor\n
                    3. Keep your head straight\n
                    4. Try to read the lowest clearley visible image using microphone: 
                    i. by covering your left eye with your left hand
                    ii. by covering your right eye with your right hand
                    iii. with both of your eyes'''
                markup: True
                font_size: '25'
                color: 0,0,0,1
        BoxLayout:
            padding: visual_acuity.space_x, 230, visual_acuity.space_x, 50
            Button:
                id: back
                text: 'Back'
                background_color: (0,.3,.3,1)
                font_size: '20'
                on_press:
                    root.manager.transition.direction= "right"
                    root.manager.current = 'select'
            Button:
                id: start
                text: 'Start Test'
                background_color: (0,.3,.3,1)
                font_size: '20'
                on_press: root.manager.current = 'snellen'

<SnellenChartWindow>
    id: snellen_chart
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: snellen_chart.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'visualAcuity.jpeg'
        Label:
            text: 'Visual Acuity Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 1
        padding: snellen_chart.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 1
            padding: snellen_chart.space_x-300, 50
            Label:
                text: "[b][color=#063d3f]Snellen chart[/color][/b]"
                markup: True
                font_size: '30'
                halign: 'center'
                size_hint_y: None
                height: 80
            Label:
                text: 
                    '''Identify the letters in the choosen line and read it out using microphone
                    Example: "[b]R, A, P, X, S[/b]"'''
                markup: True
                font_size: '20'
                halign: 'center'
                color: 0,0,0,1
        Label:
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: (300,200)
                    pos: (450,250)
                    source: 'snellen.jpeg'
        BoxLayout:
            orientation: 'vertical'
            Label:
                id: audio_test
                text: ''
                markup: True
                font_size: '20'
                color: 0,0,0,1
                halign: 'center'
            BoxLayout:
                Button:
                    id: speak
                    text: 'Speak'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: root.recording()
                    on_release: root.validate_speech()
            BoxLayout:
                Button:
                    id: back
                    text: 'Back'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press:
                        root.empty_text()
                        root.manager.transition.direction= "right"
                        root.manager.current = 'acuity'
                Button:
                    id: next
                    text: 'Next'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: 
                        root.empty_text()
                        root.manager.current = 'random_e'

<RandomEWindow>
    id: random_e_chart
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: random_e_chart.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'visualAcuity.jpeg'
        Label:
            text: 'Visual Acuity Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 2
        padding: random_e_chart.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 5
            padding: random_e_chart.space_x-300, 50
            Label:
                text: "[b][color=#063d3f]Random E chart[/color][/b]"
                markup: True
                font_size: '30'
                halign: 'center'
                size_hint_y: None
                height: 80
            Label:
                text: 
                    '''Identify which way the open sides of [b]E[/b] are facing in the choosen line and
                    read it out using microphone
                    Example: "[b]Up, Down, Left, Right[/b]"'''
                markup: True
                font_size: '20'
                halign: 'center'
                color: 0,0,0,1
        Label:
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: self.size
                    pos: (430,250)
                    source: '1randome.jpg'
        BoxLayout:
            orientation: 'vertical'
            Label:
                id: audio_test
                text: ''
                markup: True
                font_size: '20'
                color: 0,0,0,1
                halign: 'center'
            BoxLayout:
                Button:
                    id: speak
                    text: 'Speak'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: root.recording()
                    on_release: root.validate_speech()
            BoxLayout:
                Button:
                    id: back
                    text: 'Back'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press:
                        root.empty_text()
                        root.manager.transition.direction= "right"
                        root.manager.current = 'snellen'
                Button:
                    id: next
                    text: 'Next'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: 
                        root.empty_text()
                        root.manager.current = 'landolt_c' 

<LandoltCWindow>
    id: landolt_c_chart
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: landolt_c_chart.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'visualAcuity.jpeg'
        Label:
            text: 'Visual Acuity Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 1
        padding: landolt_c_chart.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 5
            padding: landolt_c_chart.space_x-300, 50
            Label:
                text: "[b][color=#063d3f]Landolt C chart[/color][/b]"
                markup: True
                font_size: '30'
                halign: 'center'
                size_hint_y: None
                height: 80
            Label:
                text: 
                    '''Identify which way the open sides of [b]C[/b] are facing in the choosen line and
                    read it out using microphone
                    Example: "[b]Up, 45 degree left down, Right[/b]"'''
                markup: True
                font_size: '20'
                halign: 'center'
                color: 0,0,0,1
        Label:
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: (300,200)
                    pos: (450,250)
                    source: 'landoltc3.jpg'
        BoxLayout:
            orientation: 'vertical'
            Label:
                id: audio_test
                text: ''
                markup: True
                font_size: '20'
                color: 0,0,0,1
                halign: 'center'
            BoxLayout:
                Button:
                    id: speak
                    text: 'Speak'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: root.recording()
                    on_release: root.validate_speech()
            BoxLayout:
                Button:
                    id: back
                    text: 'Back'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press:
                        root.empty_text()
                        root.manager.transition.direction= "right"
                        root.manager.current = 'random_e'
                Button:
                    id: next
                    text: 'Next'
                    background_color: (0,.3,.3,1)
                    font_size: '20'
                    on_press: 
                        root.empty_text()
                        root.manager.current = 'select'

<AstigmatismWindow>:
    id: astigmatism
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: astigmatism.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'astigmatism4.jpg'
        Label:
            text: 'Astigmatism Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: astigmatism.space_x+30, 200
        Label:
            size_hint_y: None
            height: 150
        Button:
            id: back
            text: 'Back'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press:
                root.manager.transition.direction= "right"
                root.manager.current = 'select'
            
<GlassCheckerWindow>:
    id: glass_checker
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: glass_checker.space_x, 660
        canvas:
            Color:
                rgba: (0,.5,.5,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: 'glass2.jpg'
        Label:
            text: 'Glass Checker Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: glass_checker.space_x+30, 200
        Label:
            size_hint_y: None
            height: 150
        Button:
            id: back
            text: 'Back'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press:
                root.manager.transition.direction= "right"
                root.manager.current = 'select'