<StartWindow>:
    id: start_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'eye2.png'
    BoxLayout:
        size_hint_y: None
        height: 70
        padding: start_window.space_x, 570
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,540)
        Label:
            text: 'Welcome to e-vision clinic'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: start_window.space_x, 180
        Label:
            text: "Follow simple steps & know about your vision "
            color: 0,0,0,1
            bold: True
            size_hint_y: None
            height: 10
        Label:
            size_hint_y: None
            height: 140
        Button:
            id: start
            text: 'Start'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'info' 
        
<InfoWindow>:
    id: info_window
    orientation: "vertical"
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: info_window.space_x, 550
        size_hint_y: None
        height: 100
        canvas:
            Color:
                rgba: (0,0.6,0.6,1)
            Ellipse:
                size: self.size
                pos: (0,500)
                source: 'eye1.jpeg'
        Label:
            text: 'Fill your information below'
            bold: True
    BoxLayout:
        padding: info_window.space_x-200, 150,info_window.space_x-200, 200
        spacing: 1
        BoxLayout:
            orientation: 'vertical'
            spacing: 20
            background_color:(0,1,1,0)
            Label:
                text: ""
                size_hint_y: None
                height: 40
            Label:
                text: "Name:"
                color: 0,0,0,1
                size_hint_y: None
                height: 40
            Label:
                text: "Age:"
                color: 0,0,0,1
                size_hint_y: None
                height: 40
            Label:
                text: "Place:"
                color: 0,0,0,1
                size_hint_y: None
                height: 40
            Label:
                text: "Contact Number:"
                color: 0,0,0,1
                size_hint_y: None
                height: 40
        BoxLayout:
            orientation: 'vertical'
            spacing: 20
            background_color:(0,1,1,0)
            Label:
                id: information
                text: ""
                markup: True
                size_hint_y: None
                height: 10
            TextInput: 
                id: name
                multiline: False
                write_tab: False
            TextInput: 
                id: age
                multiline: False
                write_tab: False
            TextInput: 
                id: place
                multiline: False
                write_tab: False
            TextInput: 
                id: number
                multiline: False
                write_tab: False
    BoxLayout:
        orientation: 'vertical'
        padding: info_window.space_x, 60
        Label:
            size_hint_y: None
            height: 430
        Button:
            id: signin
            text: 'Submit'
            background_color: (0,.3,.3,1)
            on_press: root.validate()
        
<SelectWindow>:
    id: select_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'eye3.jpg'
    BoxLayout:
        size_hint_y: None
        height: 70
        padding: select_window.space_x, 570
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,540)
        Label:
            text: 'Choose a test'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: select_window.space_x+50, 150
        Button:
            id: start
            text: 'Visual Acuity Test'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'acuity' 
        Button:
            id: start
            text: 'Astigmatism Test'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'astigma' 
        Button:
            id: start
            text: 'Glass Checker'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'glass' 
              
<VisualAcutyWindow>:
    id: visual_acuty
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 70
        padding: visual_acuty.space_x, 570
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,540)
                source: 'visualAcuty.jpeg'
        Label:
            text: 'Visual Acuty Test'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: visual_acuty.space_x+50, 150
        Label:
            size_hint_y: None
            height: 150
        Button:
            id: back
            text: 'Back'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'select'
<AstigmatismWindow>:
    id: astigmatism
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 70
        padding: astigmatism.space_x, 570
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,540)
                source: 'astigmatism1.jpg'
        Label:
            text: 'Astigmatism Test'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: astigmatism.space_x+50, 150
        Label:
            size_hint_y: None
            height: 150
        Button:
            id: back
            text: 'Back'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'select'
<GlassCheckerWindow>:
    id: glass_checker
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 70
        padding: glass_checker.space_x, 570
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,540)
                source: 'glassChecker1.jpg'
        Label:
            text: 'Glass Checker Test'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 100
        padding: glass_checker.space_x+50, 150
        Label:
            size_hint_y: None
            height: 150
        Button:
            id: back
            text: 'Back'
            background_color: (0,.3,.3,1)
            on_press: root.manager.current = 'select' 