<StartWindow>:
    id: start_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: './static/images/eye2.png'
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: start_window.space_x, 660
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,605)
        Label:
            text: 'Welcome to e-vision clinic'
            bold: True
            font_size: '35'
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: start_window.space_x, 220
        Label:
            text: "[b]Follow simple steps & know about your vision[/b]"
            color: 0,0,0,1
            font_size: '25'
            # bold: True
            markup: True
            size_hint_y: None
            height: 10
        Label:
            size_hint_y: None
            height: 140
        Button:
            id: start
            text: 'Start'
            background_color: (0,.3,.3,1)
            font_size: '25'
            # on_press: root.validate()
            on_press: root.manager.current = 'info' 
            # size_hint_y: 0.05
        
<InfoWindow>:
    id: info_window
    orientation: "vertical"
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: info_window.space_x, 660
        size_hint_y: None
        height: 100
        canvas:
            Color:
                rgba: (0,0.5,0.5,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: './static/images/eye1.jpeg'
        Label:
            text: 'Fill your information below'
            font_size: '30'
            bold: True
    BoxLayout:
        padding: info_window.space_x-200, 140,info_window.space_x-100, 190
        spacing: 10
        BoxLayout:            
            Label:
                text: "\n\nFirst Name:\n\n\nLast Name:\n\n\nAge:\n\n\nPlace:\n\n\nContact Number:"
                font_size: '20'
                color: 0,0,0,1
                halign: 'left'
        BoxLayout:
            orientation: 'vertical'
            spacing: 40
            background_color:(0,1,1,0)
            Label:
                id: information
                text: ""
                markup: True
                font_size: '22'
                size_hint_y: None
                height: 5
            TextInput: 
                id: f_name
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: l_name
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: age
                multiline: False
                write_tab: False
                font_size: '20'
                input_filter: 'int'
            TextInput: 
                id: place
                multiline: False
                write_tab: False
                font_size: '20'
            TextInput: 
                id: number
                multiline: False
                write_tab: False
                font_size: '20'
                input_filter: 'int'
    BoxLayout:
        orientation: 'vertical'
        padding: info_window.space_x, 160, info_window.space_x, 50
        Label:
            size_hint_y: None
            height: 430
        Button:
            id: signin
            text: 'Submit'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.validate()
        
<SelectWindow>:
    id: select_window
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: './static/images/eye3.jpg'
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: select_window.space_x, 660
        canvas:
            Color:
                rgba: (0,.3,.3,1)
            Ellipse:
                size: self.size
                pos: (0,605)
        Label:
            text: 'Choose a test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 120
        padding: select_window.space_x+50, 150
        Button:
            id: start
            text: 'Visual Acuity Test'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'acuity' 
        Button:
            id: start
            text: 'Astigmatism Test'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'astigma' 
        Button:
            id: start
            text: 'Glass Checker'
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.manager.current = 'glass' 
                       
  
<AcuityResultWindow>
    id: acuity_result
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: acuity_result.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: './static/images/visualAcuity.jpeg'
        Label:
            text: 'Visual Acuity Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 1
        padding: acuity_result.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 5
            padding: acuity_result.space_x-300, 10, acuity_result.space_x-300, 200
            Label:
                text: "[b][color=#063d3f]Result[/color][/b]"
                markup: True
                font_size: '34'
                halign: 'center'
                size_hint_y: None
                height: 200
            Label:
                id: vision_result
                text: ''
                markup: True
                font_size: '30'
                halign: 'center'
                color: 0,0,0,1
                bold: True
    BoxLayout:
        padding: acuity_result.space_x+30, 600, acuity_result.space_x+30, 50
        Button:
            id: show
            text: 'Show Result'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_result()
        Button:
            id: report
            text: 'Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.empty_input()


<AstigmaResultWindow>
    id: astigma_result
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: astigma_result.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: './static/images/astigmatism4.jpg'
        Label:
            text: 'Astigmatism Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 1
        padding: astigma_result.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 5
            padding: astigma_result.space_x-300, 10, astigma_result.space_x-300, 200
            Label:
                text: "[b][color=#063d3f]Result[/color][/b]"
                markup: True
                font_size: '34'
                halign: 'center'
                size_hint_y: None
                height: 200
            Label:
                id: vision_result
                text: ''
                markup: True
                font_size: '30'
                halign: 'center'
                color: 0,0,0,1
                bold: True
    BoxLayout:
        padding: astigma_result.space_x+30, 600, astigma_result.space_x+30, 50
        Button:
            id: show
            text: 'Show Result'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_result()
        Button:
            id: report
            text: 'Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.empty_input()

<GlassCheckerResultWindow>:
    id: glass_result
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint_y: None
        height: 100
        padding: glass_result.space_x, 660
        canvas:
            Color:
                rgba: (0,.6,.6,1)
            Ellipse:
                size: self.size
                pos: (0,605)
                source: './static/images/glass2.jpg'
        Label:
            text: 'Glass Checker Test'
            font_size: '30'
            bold: True
    BoxLayout:
        orientation: 'vertical'
        spacing: 1
        padding: glass_result.space_x+30, 50
        BoxLayout:
            orientation: 'vertical'
            spacing: 5
            padding: glass_result.space_x-300, 10, glass_result.space_x-300, 200
            Label:
                text: "[b][color=#063d3f]Result[/color][/b]"
                markup: True
                font_size: '34'
                halign: 'center'
                size_hint_y: None
                height: 200
            Label:
                id: vision_result
                text: ''
                markup: True
                font_size: '30'
                halign: 'center'
                color: 0,0,0,1
                bold: True
    BoxLayout:
        padding: glass_result.space_x+30, 600, glass_result.space_x+30, 50
        Button:
            id: show
            text: 'Show Result'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_result()
        Button:
            id: report
            text: 'Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.empty_input()
