<AcuityReportWindow>
    id: acuity_report
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: acuity_report.space_x, 50, acuity_report.space_x+210, 50
        canvas:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                size: (600,600)
                pos: (300, 80)
                source: './static/images/report.png'
        BoxLayout:
            padding: 200, 50, 50, 500
            Label:
                text: 'Diagnostic Report'
                font_size: '22'
                color: 0,0,0,1
                bold: True
        BoxLayout:
            BoxLayout:
                padding: -50, 60, 600, 110
                Label:
                    text: '\nName:\n\nAge:\n\nPlace:\n\nContact Number:\n\nTest Conducted:\n\nTest Result:\n\nSuggestion:'
                    font_size: '20'
                    color: 0,0,0,1
            BoxLayout:
                orientation: 'vertical'
                padding: 0, 105, 550, 155
                Label:
                    id: r_name
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_age
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 50
                Label:
                    id: r_place
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_number
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 200
                Label:
                    id: r_test
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 300
                Label:
                    id: r_result
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_suggestion
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 500
    BoxLayout:
        padding: 100, 500, 100, 50
        Label:
            text: 'Disclaimer: All tests conducted & informations given are for general informational purposes\nonly. Users should review the information with their professional health care providers.'
            font_size: '13'
            color: 0,0,0,1
    BoxLayout:
        padding: acuity_report.space_x+30, 650, acuity_report.space_x+30, 10
        Button:
            id: report
            text: 'Generate Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_report()
        Button:
            id: end
            text: 'End Test'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: 
                root.manager.current = 'select'


<AstigmaReportWindow>
    id: astigma_report
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: astigma_report.space_x, 50, astigma_report.space_x+210, 50
        canvas:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                size: (600,600)
                pos: (300, 80)
                source: './static/images/report.png'
        BoxLayout:
            padding: 200, 50, 50, 500
            Label:
                text: 'Diagnostic Report'
                font_size: '22'
                color: 0,0,0,1
                bold: True
        BoxLayout:
            BoxLayout:
                padding: -50, 60, 600, 110
                Label:
                    text: '\nName:\n\nAge:\n\nPlace:\n\nContact Number:\n\nTest Conducted:\n\nTest Result:\n\nSuggestion:'
                    font_size: '20'
                    color: 0,0,0,1
            BoxLayout:
                orientation: 'vertical'
                padding: 0, 105, 550, 155
                Label:
                    id: r_name
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_age
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 50
                Label:
                    id: r_place
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_number
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 200
                Label:
                    id: r_test
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 300
                Label:
                    id: r_result
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_suggestion
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 500
    BoxLayout:
        padding: 100, 500, 100, 50
        Label:
            text: 'Disclaimer: All tests conducted & informations given are for general informational purposes\nonly. Users should review the information with their professional health care providers.'
            font_size: '13'
            color: 0,0,0,1
    BoxLayout:
        padding: astigma_report.space_x+30, 650, astigma_report.space_x+30, 10
        Button:
            id: report
            text: 'Generate Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_report()
        Button:
            id: end
            text: 'End Test'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: 
                root.manager.current = 'select'


<GlassReportWindow>
    id: glass_report
    orientation: "vertical"
    spacing: 20
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        padding: glass_report.space_x, 50, glass_report.space_x+210, 50
        canvas:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                size: (600,600)
                pos: (300, 80)
                source: './static/images/report.png'
        BoxLayout:
            padding: 200, 50, 50, 500
            Label:
                text: 'Diagnostic Report'
                font_size: '22'
                color: 0,0,0,1
                bold: True
        BoxLayout:
            BoxLayout:
                padding: -50, 60, 600, 110
                Label:
                    text: '\nName:\n\nAge:\n\nPlace:\n\nContact Number:\n\nTest Conducted:\n\nTest Result:\n\nSuggestion:'
                    font_size: '20'
                    color: 0,0,0,1
            BoxLayout:
                orientation: 'vertical'
                padding: 0, 105, 550, 155
                Label:
                    id: r_name
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_age
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 50
                Label:
                    id: r_place
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_number
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 200
                Label:
                    id: r_test
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 300
                Label:
                    id: r_result
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 400
                Label:
                    id: r_suggestion
                    text: ''
                    font_size: '20'
                    color: 0,0,0,1
                    text_size: self.size
                    halign: 'left'
                    size_hint_x: None
                    width: 500
    BoxLayout:
        padding: 100, 500, 100, 50
        Label:
            text: 'Disclaimer: All tests conducted & informations given are for general informational purposes\nonly. Users should review the information with their professional health care providers.'
            font_size: '13'
            color: 0,0,0,1
    BoxLayout:
        padding: glass_report.space_x+30, 650, glass_report.space_x+30, 10
        Button:
            id: report
            text: 'Generate Report'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: root.final_report()
        Button:
            id: end
            text: 'End Test'
            size: self.size
            background_color: (0,.3,.3,1)
            font_size: '20'
            on_press: 
                root.manager.current = 'select'